# BindPlane Server Configuration
port: 3001
host: 0.0.0.0

# Authentication configuration
auth:
  type: basic
  basic:
    username: ${BINDPLANE_USERNAME}
    password: ${BINDPLANE_PASSWORD}

# License key (required)
license: ${BINDPLANE_LICENSE}

# Backend storage configuration
store:
  type: postgres
  postgres:
    host: bindplane-postgres
    port: 5432
    database: bindplane
    username: bindplane
    password: ${POSTGRES_PASSWORD}
    sslmode: disable
    maxConnections: 20

# Alternative: Use file storage (for simpler setups)
# store:
#   type: file
#   file:
#     path: /var/lib/bindplane

# Remote URL for collectors to connect
remoteURL: http://bindplane:3001

# Session management
sessions:
  secret: ${SESSIONS_SECRET}

# Transform agent configuration
transform_agent:
  agents:
    - name: bindplane-collector
      type: collector
      host: bindplane-collector:4568
      port: 4568
      protocol: http

# Event bus configuration (for multi-instance setups)
# eventbus:
#   type: nats
#   nats:
#     server: nats://localhost:4222

# Logging configuration
logging:
  level: info
  format: json
  output: stdout

# Telemetry configuration
telemetry:
  metrics:
    enabled: true
    port: 9090
    path: /metrics